# Generated by Django 4.2 on 2023-05-16 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_project_code1_project_code2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='code1',
            new_name='file1',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='code2',
            new_name='file2',
        ),
    ]
